version: "3.8"

services:
  app:
    build: /app
    container_name: app
    command: uvicorn app:app --host 0.0.0.0 --port ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    volumes:
      - ./.env:/.env
    networks:
      network:

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: postgres -p ${POSTGRES_PORT}
    ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      network:

networks:
  network:
